var spin3 = { 
"isSuccess":true,
	"messageTypeId":-2,
	"errodCode":-2147483648,
	"responseId":5,
	"errorString":null,
	"spinRecords":[ 
{  
         "isBonus":false,
	"casinoContext":{  
            "betMultipliers":[ 

],
	"gameLevelUpDetails":[ 

],
	"playerExperience":10077403443330,
		"gameExperience":14546157890,
		"gameLevelUpSpins":-1,
		"vpBetMultipliers":[ 

],
	"gameCoins":-1,
		"gameLevel":-1,
		"credits":-1,
		"gameLevelThresholds":[ 

],
	"harvest":-1,
		"lobbySpins":-1,
		"playerLevelUpDetails":[ 

],
	"gameId":1142,
		"playerLevelThresholds":[ 

],
	"playerLevel":-1
},
	"stops":[
            135,
			101,
			78,
			2,
			32
],
	"tumblingOccurs":false,
	"wins":[  
            {  
               "spinsValue":0,
				"paylineIndex":2,
				"ofAKindCount":3,
				"type":{  
                  "id":2,
					"name":"Payline",
					"codec":{ 

				}
			},
				"isRightToLeft":false,
				"winningType":10,
				"creditsValue":2310000
			},
	{  
               "spinsValue":0,
		"paylineIndex":5,
		"ofAKindCount":3,
		"type":{  
                  "id":2,
			"name":"Payline",
			"codec":{ 

		}
	},
		"isRightToLeft":false,
		"winningType":10,
		"creditsValue":2310000
	},
	{  
               "spinsValue":0,
		"paylineIndex":8,
		"ofAKindCount":3,
		"type":{  
                  "id":2,
			"name":"Payline",
			"codec":{ 

		}
	},
		"isRightToLeft":false,
		"winningType":10,
		"creditsValue":2310000
	},
	{  
               "spinsValue":0,
		"paylineIndex":18,
		"ofAKindCount":3,
		"type":{  
                  "id":2,
			"name":"Payline",
			"codec":{ 

		}
	},
		"isRightToLeft":false,
		"winningType":10,
		"creditsValue":2310000
	},
	{  
               "spinsValue":0,
		"paylineIndex":20,
		"ofAKindCount":3,
		"type":{  
                  "id":2,
			"name":"Payline",
			"codec":{ 

		}
	},
		"isRightToLeft":false,
		"winningType":10,
		"creditsValue":2310000
	},
	{  
               "spinsValue":0,
		"paylineIndex":26,
		"ofAKindCount":3,
		"type":{  
                  "id":2,
			"name":"Payline",
			"codec":{ 

		}
	},
		"isRightToLeft":false,
		"winningType":10,
		"creditsValue":2310000
	},
	{  
               "spinsValue":0,
		"paylineIndex":34,
		"ofAKindCount":3,
		"type":{  
                  "id":2,
			"name":"Payline",
			"codec":{ 

		}
	},
		"isRightToLeft":false,
		"winningType":10,
		"creditsValue":2310000
	}
],
	"respinTriggered":false,
	"bonusTriggered":false,
	"spinsWon":0,
	"replacement":"ByteArray",
	"isRespin":false,
	"creditsWon":16170000
}
],
"startingCredits":75913806436250,
	"payload":null,
	"sourceRequest":{  
      "gameId":1142,
		"bonusChoice":-1,
		"messageTypeId":-2,
		"requestId":5,
		"casinoContext":{  
         "isAutoPlay":false,
			"spacebarUsed":true,
			"maxBetUsed":false
	},
	"isBonusSet":false,
		"isBonus":false,
		"baseChoice":-1,
		"bet":{  
         "casinoContext":null,
			"totalBet":92400000,
			"multiplier":2310000,
			"linesPlayed":40
	},
	"gaffe":null
},
"totalCreditsWon":16170000,
	"casinoContext":null,
	"errorUUID":null,
	"totalSpinsWon":0,
	"credits":75913730206250
};

module.exports = spin3;